services:
#    address_formatting.example:
#        class: CitizenKey\AddressFormatterBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    address.formatter:
        class: CitizenKey\AddressFormatterBundle\AddressFormatter
        arguments: ['@service_container']
